name: lab1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/BASIC_POPLIN_SHIRT.png
    - assets/COMBINATION_T-SHIRT_WITH_ZIPPER_VEST.png
    - assets/DOUBLE_WAIST_WIDE_LEG_PANTS.png
    - assets/SOFT_POCKET_JACKET.png
    - assets/Z1975_HIGH_RISE_WIDE_LEG_JEANS.png
    - assets/DENIM_VEST.png
    - assets/BELTED_WOOL_BLEND_COAT.png
    - assets/GOLD_BUTTON_KNITTED_VEST_TOP.png

  uses-material-design: true



